# 项目信息配置
SPECIES: "Zea_mays"  # 物种名称，请从下列选取目标物种的拉丁文填入，例如：Zea_mays（玉米）或其他物种的名称

###
# 以下是物种和对应的拉丁文名：
# Homo_sapiens: 人类
# Mus_musculus: 小鼠
# Arabidopsis_thaliana: 拟南芥
# Anopheles: 按蚊
# Bos_taurus: 牛
# Caenorhabditis_elegans: 秀丽隐杆线虫
# Canis_familiaris: 犬
# Drosophila_melanogaster: 苍蝇
# Danio_rerio: 斑马鱼
# Escherichia_coli_K12: 大肠杆菌 K12
# Escherichia_coli_Sakai: 大肠杆菌 Sakai
# Gallus_gallus: 鸡
# Macaca_mulatta: 恒河猴
# Pan_troglodytes: 黑猩猩
# Rattus_norvegicus: 大鼠
# Saccharomyces_cerevisiae: 酵母
# Sus_scrofa: 猪
# Xenopus_laeviss: 爪蟾
# Oryza_sativa: 水稻
# Zea_mays: 玉米
###

# 项目目录全路径，用以输出RNA-seq分析的结果
PROJECT_DIR: "/home/data/t210528/Projects/RNA-seq/Zea_mays"

# 输入的基因型数据路径，存储原始的基因型数据（如FASTQ文件）
GENOTYPIC_DATA: "{PROJECT_DIR}/input_data/genotypic_data"

# 输入的表型数据路径，存储样本的表型信息，格式需要为csv格式，第一列是样本名称，列名为sample，第二列是表型信息(内容需要改为Contrast或者Experimental)，列名为information
PHENOTYPIC_DATA: "{PROJECT_DIR}/input_data/phenotypic_data/phenotypic_data.csv"

# 存放日志文件的目录，记录Snakemake执行过程中的日志信息
LOGS_DIR: "{PROJECT_DIR}/logs"

# 上游分析结果的目录，包含数据清洗、质量控制、比对等步骤的输出
UPSTREAM_ANALYSIS: "{PROJECT_DIR}/Upstream_Analysis"

# 下游分析结果的目录，包含差异分析、富集分析等步骤的输出
DOWNSTREAM_ANALYSIS: "{PROJECT_DIR}/Downstream_Analysis"

# 基因注释文件，通常是GTF格式，从NCBI获取后解压
ANNOTATION_FILE: "{PROJECT_DIR}/references/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gtf"

# 参考基因组文件，通常是fna格式，从NCBI获取后解压
GENOME_FILE: "{PROJECT_DIR}/references/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.fna"

# Apptainer容器镜像文件的路径，用于确保数据分析环境的一致性
SINGULARITY_IMAGE: "{PROJECT_DIR}/Apptainer/rna_seq.sif"
